### ISSUE TITLE
maven extraction on guava fails to find java.lang when indexing

### ISSUE THREAD

**Issue by danielmoy-google** [kythe/kythe#3510]
Repro:

1. extract maven (either locally or following example gcb instructions at kythe/extractors/gcp/examples)
2. `bazel build kythe/java/com/google/devtools/kythe/analyzers/java:indexer`
3. `bazel-bin/kythe/java/com/google/devtools/kythe/analyzers/java/indexer some.kzip`

Yields:

```
Exception in thread "main" com.google.devtools.kythe.platform.shared.AnalysisException: Exception analyzing file: ObjectArrays.java
	at com.google.devtools.kythe.analyzers.java.KytheJavacAnalyzer.analyzeFile(KytheJavacAnalyzer.java:142)
	at com.google.devtools.kythe.platform.java.JavacAnalyzer.analyzeCompilationUnit(JavacAnalyzer.java:63)
	at com.google.devtools.kythe.analyzers.java.KytheJavacAnalyzer.analyzeCompilationUnit(KytheJavacAnalyzer.java:111)
	at com.google.devtools.kythe.platform.java.JavacAnalysisDriver.analyze(JavacAnalysisDriver.java:64)
	at com.google.devtools.kythe.analyzers.java.JavaIndexer.analyzeCompilation(JavaIndexer.java:181)
	at com.google.devtools.kythe.analyzers.java.JavaIndexer.main(JavaIndexer.java:120)
Caused by: com.sun.tools.javac.util.FatalError: Fatal Error: Unable to find package java.lang in classpath or bootclasspath
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$ImportsPhase.resolveImports(Unknown Source)
...
```

**Comment by schroederc** [comment]
What does the CompilationUnit look like?  In particular, the `JavaDetails`.

**Comment by danielmoy-google** [comment]
Can't speak for jedmonds@spotify, but let me look at guava

**Comment by danielmoy-google** [comment]
```
$ bazel build kythe/go/platform/tools/viewindex/viewindex
$ bazel-bin/kythe/go/platform/tools/viewindex/viewindex ~/test/guava/merged/merged.kzip | jq

# grep on JavaDetails:

grep -B 4 -A 20 JavaDetails ~/test/guava/merged/merged.json
  ],
  "output_key": "guava-gwt/target/classes",
  "details": [
    {
      "@type": "kythe.io/proto/kythe.proto.JavaDetails",
      "classpath": [
        "guava/target/classes/",
        "!CLASS_PATH_JAR!"
      ],
      "sourcepath": [
        "guava-gwt/src"
      ]
    },
    {
      "@type": "kythe.io/proto/kythe.proto.BuildDetails",
      "build_target": "#3420233d48e675fbca22c358b78b41d4ff0d1bed353c3407ffdb589f54357d94"
    }
  ]
}

--
  ],
  "output_key": "guava-testlib/target/classes",
  "details": [
    {
      "@type": "kythe.io/proto/kythe.proto.JavaDetails",
      "classpath": [
        "guava/target/classes/",
        "!CLASS_PATH_JAR!"
      ],
      "sourcepath": [
        "guava-testlib/src"
      ]
    },
    {
      "@type": "kythe.io/proto/kythe.proto.BuildDetails",
      "build_target": "#47b1abdeeb3ee99fcd583421b6b0d37d82fd7e42b9a55ee324ffc70f78076b48"
    }
  ]
}


--
  ],
  "output_key": "guava/target/classes",
  "details": [
    {
      "@type": "kythe.io/proto/kythe.proto.JavaDetails",
      "classpath": [
        "!CLASS_PATH_JAR!"
      ],
      "sourcepath": [
        "guava/src"
      ],
      "bootclasspath": [
        "!PLATFORM_CLASS_PATH_JAR!"
      ]
    },
    {
      "@type": "kythe.io/proto/kythe.proto.BuildDetails",
      "build_target": "#ec2878c2197e1da92c707d1532041fa89446726d7cc15089603b0cf908f38b59"
    }
  ]
}
```

**Comment by danielmoy-google** [comment]
Probably not the best example from guava because gwt, can look at another one

**Comment by danielmoy-google** [comment]
Others are similar actually.  Here's an example with only one pom module:

```
bazel-bin/kythe/go/platform/tools/viewindex/viewindex ~/test/guava/single/ec2878c2197e1da92c707d1532041fa89446726d7cc15089603b0cf908f38b59.kzip | jq . | grep -B 3 -A 20 JavaDetails
  "output_key": "guava/target/classes",
  "details": [
    {
      "@type": "kythe.io/proto/kythe.proto.JavaDetails",
      "classpath": [
        "!CLASS_PATH_JAR!"
      ],
      "sourcepath": [
        "guava/src"
      ],
      "bootclasspath": [
        "!PLATFORM_CLASS_PATH_JAR!"
      ]
    },
    {
      "@type": "kythe.io/proto/kythe.proto.BuildDetails",
      "build_target": "#ec2878c2197e1da92c707d1532041fa89446726d7cc15089603b0cf908f38b59"
    }
  ]
}
```

**Comment by johnedmonds** [comment]
Seems to be related somehow to this line: https://github.com/kythe/kythe/blob/master/kythe/java/com/google/devtools/kythe/platform/java/JavacOptionsUtils.java#L163

Deleting it solves the problem on my machine for a trivial repository. My guess is that since we're running with Java 11, having stuff like rt.jar on the classpath just complicates things (since java 9+ uses modules instead of rt.jar and friends).

I'm still looking at it but hopefully that provides a big enough hint for a more complete solution.

**Comment by shahms** [comment]
Yes; the extraction (and likely indexing) are not currently compatible with JDK 11.

**Comment by shahms** [comment]
Er, modules.

**Comment by johnedmonds** [comment]
Still seems to fail when running with java 8 though.

**Comment by danielmoy-google** [comment]
Yea there are two separate issues here.  One is jdk 11 / modules / etc support - (kythe/issues/3095, kythe/issues/3075, and we have an internal bug on this as well).

The other issue is this issue, which is about maven (and similarly gradle) needing to support extraction referencing other packages/modules (java.lang as in the title, but this also affects other external deps as well).

**Comment by johnedmonds** [comment]
Okay, thanks for the links! That make a lot of sense. So just to check my understanding: Kythe wants to support Maven's ability to alter the bootclasspath (for Java <=8) or the module overrides (for Java > 8). But because we're trying to alter javac (11)'s boot classpath with Java 8's boot classpath (which are basically paths to jars that don't exist in Java 11) we're essentially _deleting_ the entire boot classpath for Java 11 which causes java.lang to no longer be found.

I'm wondering if the solution is to modify JavaDetails to allow specifying which modules to override and how. Or perhaps if it's reasonable to implement a shorter-term solution for Java 11 given that most Maven projects don't want to override javac's modules and the current implementation which attempts to override javac 11's bootclasspath prevents indexing from happening at all. Maybe something like only attempting to override the bootclasspath (https://github.com/kythe/kythe/blob/2853c7acad6bf9d86b9f2935ab20c83b55c268de/kythe/java/com/google/devtools/kythe/platform/java/JavacOptionsUtils.java#L163) if we detect that we're running on Java 8.
