### ISSUE TITLE
build //kythe/web/ui fails

### ISSUE THREAD

**Issue by kamahen** [kythe/kythe#3636]
AFAIK, I've installed all the prereqs, including `openjdk-8-jdk`; but `java/sql/Timestamp` appears to be missing and I am clueless as to how to install it (on Ubuntu 18.04).
```
$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

$ bazel build --verbose_failures //kythe/web/ui
Loading: 
Loading: 0 packages loaded
Analyzing: target //kythe/web/ui:ui (0 packages loaded, 0 targets configured)
INFO: Analysed target //kythe/web/ui:ui (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
bazel: Entering directory `/home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/execroot/io_kythe/'
[0 / 2] [-----] BazelWorkspaceStatusAction stable-status.txt
INFO: From Executing genrule //kythe/web/ui:prod-js:
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core__init.load(Unknown Source)
	at clojure.core__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.lang.RT.doInit(RT.java:454)
	at clojure.lang.RT.<clinit>(RT.java:330)
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.ClassNotFoundException: java/sql/Timestamp
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2167)
	at clojure.instant$loading__5340__auto____6637.invoke(instant.clj:9)
	at clojure.instant__init.load(Unknown Source)
	at clojure.instant__init.<clinit>(Unknown Source)
	... 22 more
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core__init.load(Unknown Source)
	at clojure.core__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.lang.RT.doInit(RT.java:454)
	at clojure.lang.RT.<clinit>(RT.java:330)
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.ClassNotFoundException: java/sql/Timestamp
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2167)
	at clojure.instant$loading__5340__auto____6637.invoke(instant.clj:9)
	at clojure.instant__init.load(Unknown Source)
	at clojure.instant__init.<clinit>(Unknown Source)
	... 22 more
mv: cannot stat 'kythe/web/ui/resources/public/js/main.js': No such file or directory
ERROR: /home/peter/src/kythe/kythe/web/ui/BUILD:15:1: declared output 'kythe/web/ui/resources/public/js/main.js' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
ERROR: /home/peter/src/kythe/kythe/web/ui/BUILD:15:1: not all outputs were created or valid
bazel: Leaving directory `/home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/execroot/io_kythe/'
Target //kythe/web/ui:ui failed to build
INFO: Elapsed time: 1.115s, Critical Path: 0.75s
INFO: 1 process: 1 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by shahms** [comment]
#3600 

$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

Leiningen only supports JDK8 and the install script finds the first one in PATH which, in this case, is jdk10

**Comment by kamahen** [comment]
I tried forcing java8, and still get the same problem:

```
$ (export PATH="/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH"; type java; java -version; bazel build //kythe/web/ui)
java is /usr/lib/jvm/java-8-openjdk-amd64/bin/java
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
Loading: 
Loading: 0 packages loaded
Analyzing: target //kythe/web/ui:ui (0 packages loaded, 0 targets configured)
INFO: Analysed target //kythe/web/ui:ui (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
bazel: Entering directory `/home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/execroot/io_kythe/'
[0 / 1] [-----] BazelWorkspaceStatusAction stable-status.txt
INFO: From Executing genrule //kythe/web/ui:prod-js:
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core__init.load(Unknown Source)
	at clojure.core__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.lang.RT.doInit(RT.java:454)
	at clojure.lang.RT.<clinit>(RT.java:330)
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.ClassNotFoundException: java/sql/Timestamp
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2167)
	at clojure.instant$loading__5340__auto____6637.invoke(instant.clj:9)
	at clojure.instant__init.load(Unknown Source)
	at clojure.instant__init.<clinit>(Unknown Source)
	... 22 more
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core__init.load(Unknown Source)
	at clojure.core__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.lang.RT.doInit(RT.java:454)
	at clojure.lang.RT.<clinit>(RT.java:330)
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.ClassNotFoundException: java/sql/Timestamp
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2167)
	at clojure.instant$loading__5340__auto____6637.invoke(instant.clj:9)
	at clojure.instant__init.load(Unknown Source)
	at clojure.instant__init.<clinit>(Unknown Source)
	... 22 more
mv: cannot stat 'kythe/web/ui/resources/public/js/main.js': No such file or directory
ERROR: /home/peter/src/kythe/kythe/web/ui/BUILD:15:1: declared output 'kythe/web/ui/resources/public/js/main.js' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
ERROR: /home/peter/src/kythe/kythe/web/ui/BUILD:15:1: not all outputs were created or valid
bazel: Leaving directory `/home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/execroot/io_kythe/'
Target //kythe/web/ui:ui failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.804s, Critical Path: 0.65s
INFO: 1 process: 1 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by shahms** [comment]
Try it with `--verbose_failures` and `--sandbox_debug`; you'll likely find that PATH inside the sandbox is not the same as outside.

**Comment by shahms** [comment]
PR #3638 should also fix this (by including the path to the java binary found during configuration in the wrapper script)

**Comment by kamahen** [comment]
I modified the BUILD file to output the java version, and it's not Java 8. What might be overriding the PATH? (it's just `/bin:/usr/bin`)

Anyway, this modification worked:
```
diff --git a/kythe/web/ui/BUILD b/kythe/web/ui/BUILD
index 77131bbb..6bca828c 100644
--- a/kythe/web/ui/BUILD
+++ b/kythe/web/ui/BUILD
@@ -22,7 +22,7 @@ genrule(
         "resources/public/js/main.js",
         "resources/public/js/licenses.txt",
     ],
-    cmd = "$(location @org_leiningen//:leinbuild) $(location :project.clj) $(OUTS)",
+    cmd = 'PATH="/usr/lib/jvm/java-8-openjdk-amd64/bin:$$PATH" $(location @org_leiningen//:leinbuild) $(location :project.clj) $(OUTS)',
     heuristic_label_expansion = False,
     tags = ["manual"],
     tools = ["@org_leiningen//:leinbuild"],
```

**Comment by shahms** [comment]
Bazel sets PATH inside the sandbox; see my earlier comment for debugging that.

**Comment by kamahen** [comment]
I tried the extra debug flags, but I didn't see anything obvious about PATH being set. And I didn't see an obvious an obvious Bazel flag to set.

Anyway, I have a workaround, and that's good enough for now.

**Comment by shahms** [comment]
with PR #3639 you'll see:

```
  (cd /..../execroot/io_kythe && \
  exec env - \
    PATH=/bin:/usr/bin \
    TMPDIR=/tmp \
```

**Comment by kamahen** [comment]
I think you mean PR #3638 and the use of `LEIN_JAVA_CMD` ?
(I couldn't see the `execroot/io_kythe` stuff; maybe it hasn't been committed yet?)

**Comment by shahms** [comment]
I meant #3639; the `set -e` causes the script to exit with failure which causes Bazel (when run with --verbose_failures) to print the command used to invoke the script, including the environment.

**Comment by kamahen** [comment]
Confirming that it fails with a useful message embedded in the output:
```
$ nice bazel build //kythe/web/ui; bazel shutdown
Starting local Bazel server and connecting to it...
ERROR: /home/peter/src/kythe/kythe/web/ui/BUILD:15:1: no such package '@org_leiningen//': Traceback (most recent call last):
	File "/home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/external/io_kythe/third_party/leiningen/lein_repo.bzl", line 2
		_check_jdk(repository_ctx)
	File "/home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/external/io_kythe/third_party/leiningen/lein_repo.bzl", line 104, in _check_jdk
		fail("Leiningen requires JDK8, found:...))
Leiningen requires JDK8, found: 2018-07-17 (with LEIN_JAVA_CMD=/usr/bin/java) and referenced by '//kythe/web/ui:prod-js'
ERROR: Analysis of target '//kythe/web/ui:ui' failed; build aborted: no such package '@org_leiningen//': Traceback (most recent call last):
	File "/home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/external/io_kythe/third_party/leiningen/lein_repo.bzl", line 2
		_check_jdk(repository_ctx)
	File "/home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/external/io_kythe/third_party/leiningen/lein_repo.bzl", line 104, in _check_jdk
		fail("Leiningen requires JDK8, found:...))
Leiningen requires JDK8, found: 2018-07-17 (with LEIN_JAVA_CMD=/usr/bin/java)
INFO: Elapsed time: 4.017s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (4 packages loaded, 19 targets configured)
    Fetching @org_leiningen; fetching
```

**Comment by kamahen** [comment]
But setting `LEIN_JAVA_CMD` isn't sufficient ...

```$ LEIN_JAVA_CMD=/usr/lib/jvm/java-8-openjdk-amd64/bin/java nice bazel build --sandbox_debug --verbose_failures //kythe/web/ui; bazel shutdown

Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Analyzing: target //kythe/web/ui:ui (1 packages loaded, 0 targets configured)
Analyzing: target //kythe/web/ui:ui (21 packages loaded, 674 targets configured)
INFO: Analysed target //kythe/web/ui:ui (22 packages loaded, 674 targets configured).
INFO: Found 1 target...
bazel: Entering directory `/home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/execroot/io_kythe/'
[1 / 3] [-----] BazelWorkspaceStatusAction stable-status.txt
ERROR: /home/peter/src/kythe/kythe/web/ui/BUILD:15:1: Executing genrule //kythe/web/ui:prod-js failed (Exit 2) linux-sandbox failed: error executing command 
  (cd /home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/sandbox/linux-sandbox/1/execroot/io_kythe && \
  exec env - \
    PATH=/bin:/usr/bin \
    TMPDIR=/tmp \
  /home/peter/.cache/bazel/_bazel_peter/install/6f98dd1afced7c8dc211ce7a461c786c/_embedded_binaries/linux-sandbox -t 15 -w /home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/sandbox/linux-sandbox/1/execroot/io_kythe -w /tmp -w /dev/shm -D -- /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; PATH="/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH" bazel-out/host/bin/external/org_leiningen/leinbuild kythe/web/ui/project.clj bazel-out/k8-fastbuild/genfiles/kythe/web/ui/resources/public/js/main.js bazel-out/k8-fastbuild/genfiles/kythe/web/ui/resources/public/js/licenses.txt'): linux-sandbox failed: error executing command 
  (cd /home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/sandbox/linux-sandbox/1/execroot/io_kythe && \
  exec env - \
    PATH=/bin:/usr/bin \
    TMPDIR=/tmp \
  /home/peter/.cache/bazel/_bazel_peter/install/6f98dd1afced7c8dc211ce7a461c786c/_embedded_binaries/linux-sandbox -t 15 -w /home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/sandbox/linux-sandbox/1/execroot/io_kythe -w /tmp -w /dev/shm -D -- /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; PATH="/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH" bazel-out/host/bin/external/org_leiningen/leinbuild kythe/web/ui/project.clj bazel-out/k8-fastbuild/genfiles/kythe/web/ui/resources/public/js/main.js bazel-out/k8-fastbuild/genfiles/kythe/web/ui/resources/public/js/licenses.txt')
src/main/tools/linux-sandbox.cc:154: linux-sandbox-pid1 has PID 24672
src/main/tools/linux-sandbox-pid1.cc:175: working dir: /home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/sandbox/linux-sandbox/1/execroot/io_kythe
src/main/tools/linux-sandbox-pid1.cc:194: writable: /home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/sandbox/linux-sandbox/1/execroot/io_kythe
src/main/tools/linux-sandbox-pid1.cc:194: writable: /tmp
src/main/tools/linux-sandbox-pid1.cc:194: writable: /dev/shm
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /dev
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /dev/pts
src/main/tools/linux-sandbox-pid1.cc:265: remount rw: /dev/shm
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /dev/mqueue
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /dev/hugepages
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /run
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /run/lock
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /run/snapd/ns
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /run/user/1000
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /run/user/1000/gvfs
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/kernel/security
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/unified
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/systemd
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/cpu,cpuacct
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/rdma
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/net_cls,net_prio
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/cpuset
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/blkio
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/freezer
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/devices
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/hugetlb
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/perf_event
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/pids
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/cgroup/memory
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/pstore
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/kernel/debug
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/fs/fuse/connections
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /sys/kernel/config
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /proc
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /proc/sys/fs/binfmt_misc
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /proc/sys/fs/binfmt_misc
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/canonical-livepatch/58
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/gtk-common-themes/1122
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/gnome-system-monitor/57
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/gtk-common-themes/818
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/core18/731
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/core/6405
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/gnome-logs/45
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/gnome-characters/206
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/gimp/130
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/gnome-characters/139
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/core/6531
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/gnome-calculator/260
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/gnome-3-26-1604/74
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/gnome-3-26-1604/78
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/gnome-3-28-1804/23
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/gnome-3-26-1604/82
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/gnome-logs/57
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/core/6350
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/core18/782
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/gnome-system-monitor/70
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/gnome-calculator/352
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /snap/gtk-common-themes/1198
src/main/tools/linux-sandbox-pid1.cc:265: remount ro: /media/disk2
src/main/tools/linux-sandbox-pid1.cc:265: remount rw: /home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/sandbox/linux-sandbox/1/execroot/io_kythe
src/main/tools/linux-sandbox-pid1.cc:265: remount rw: /home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/sandbox/linux-sandbox/1/execroot/io_kythe
src/main/tools/linux-sandbox-pid1.cc:265: remount rw: /tmp
src/main/tools/linux-sandbox-pid1.cc:265: remount rw: /dev/shm
src/main/tools/process-tools.cc:118: sigaction(32, &sa, nullptr) failed
src/main/tools/process-tools.cc:118: sigaction(33, &sa, nullptr) failed
bazel-out/host/bin/external/org_leiningen/leinbuild: 10: set: Illegal option -o pipefail
src/main/tools/linux-sandbox-pid1.cc:437: waitpid returned 2
src/main/tools/linux-sandbox-pid1.cc:457: child exited with code 2
src/main/tools/linux-sandbox.cc:204: child exited normally with exitcode 2
bazel: Leaving directory `/home/peter/.cache/bazel/_bazel_peter/836c07f179996fd91f0eefe24af5a330/execroot/io_kythe/'
Target //kythe/web/ui:ui failed to build
INFO: Elapsed time: 3.922s, Critical Path: 0.15s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by shahms** [comment]
`bazel-out/host/bin/external/org_leiningen/leinbuild: 10: set: Illegal option -o pipefail`

You have a weird shell; this is unrelated to the Java version.

**Comment by kamahen** [comment]
I suspect that somehow Bazel is using `sh` instead of `bash`; `sh` doesn't have `pipefail`. 
(I'm running a pretty vanilla Ubuntu 18.04.)

I tried `bazel build --shell_executable=/bin/bash ...` but that didn't help.

**Comment by shahms** [comment]
#3640

**Comment by kamahen** [comment]
That seems to have worked (I haven't yet done a full test of the generated web/ui with the http_server, but will try to do that "soon").
Thank-you!
