### ISSUE TITLE
Java: shallow signature generation, or support annotation processing, or ...?

### ISSUE THREAD

**Issue by robinp** [kythe/kythe#4464]
Environment: Kythe `v.0.0.41` and javac `11.0.6`.

I'm indexing multiple gradle builds. I'm auto-generating `vnames.json` files so that the various ways a given unit results in the same VNames. (by source code from same project; by `class` files from subproject; by `jar` files from other projects etc). It works fine, except one detail:

Class `Foo` uses Lombok annotation processing to generate getters/setters/etc.

When running the indexer, I notice that the generated signature for class `Foo` mismatches inside its own project and other referring projects. My assumption is that the same project uses the non-processed sources to calculate the signature, while other projects use the already-processed class files. If the methods are taken account into the class signature generation, that can cause a mismatch. I found Kythe's [SignatureGenerator](https://github.com/kythe/kythe/blob/master/kythe/java/com/google/devtools/kythe/platform/java/helpers/SignatureGenerator.java), but got lost.

Next, I then tried to pass the `--emit_jvm_signatures` flag to the java_indexer. This makes the signatures match and finally I would get cross-references. But now a class `Bar` (which also has Lombok processing) fails to get a signature using the following exception, bringing indexing to halt:

```
Exception in thread "main" com.google.devtools.kythe.platform.shared.AnalysisException: Exception analyzing file: Foo.java
        at com.google.devtools.kythe.analyzers.java.KytheJavacAnalyzer.analyzeFile(KytheJavacAnalyzer.java:161)
        at com.google.devtools.kythe.platform.java.JavacAnalyzer.analyzeCompilationUnit(JavacAnalyzer.java:63)
        at com.google.devtools.kythe.analyzers.java.KytheJavacAnalyzer.analyzeCompilationUnit(KytheJavacAnalyzer.java:120)
        at com.google.devtools.kythe.platform.java.JavacAnalysisDriver.analyze(JavacAnalysisDriver.java:80)  
        at com.google.devtools.kythe.analyzers.java.JavaIndexer.analyzeCompilation(JavaIndexer.java:178)   
        at com.google.devtools.kythe.analyzers.java.JavaIndexer.main(JavaIndexer.java:113)            
Caused by: java.lang.AssertionError: typeSig ERROR                                                    
        at jdk.compiler/com.sun.tools.javac.code.Types$SignatureGenerator.assembleSig(Types.java:5119) 
        at com.google.devtools.kythe.platform.java.helpers.SignatureGenerator$SigGen.addSignature(SignatureGenerator.java:574)
        at com.google.devtools.kythe.platform.java.helpers.SignatureGenerator$SigGen.getSignature(SignatureGenerator.java:560)                                                                              
        at com.google.devtools.kythe.platform.java.helpers.SignatureGenerator.getSignature(SignatureGenerator.java:184)
        at com.google.devtools.kythe.analyzers.java.KytheTreeScanner.getJavaNode(KytheTreeScanner.java:1115)         
        at com.google.devtools.kythe.analyzers.java.KytheTreeScanner.getRefNode(KytheTreeScanner.java:1209)
        at com.google.devtools.kythe.analyzers.java.KytheTreeScanner.emitNameUsage(KytheTreeScanner.java:1167)
        at com.google.devtools.kythe.analyzers.java.KytheTreeScanner.visitSelect(KytheTreeScanner.java:787)
        at com.google.devtools.kythe.analyzers.java.KytheTreeScanner.visitSelect(KytheTreeScanner.java:116)                                                                                                 
        at com.google.devtools.kythe.platform.java.helpers.JCTreeScanner.visitMemberSelect(JCTreeScanner.java:580)
```
`Bar`'s source code tries to use a processor-generated method. If I have a look at the references generated until the exception, I see this:

```
@Data 
public class Bar {
  private String x;
  // ... other fields

  public Bar(Bar other) {
    setX(other.getX());         // <---- After and including 'getX', no references were emitted.
                                //       'setX' and 'other' still had references.
    // ... other setters
  }
}
```
I wonder if the error is fundamentally caused by not indexing the processed classes? Due to Lombok, that seems to be necessary eventually.

If I look at the extraction with `kzip view`, there are no annotation processors listed in the arguments (while the Javac / Java extractor invocation contains them, as I log those). Looking at `JavaCompilationUnitExtractor.java` it seems that the processor list is only used to verify if the compilation succeeded, but the processors are otherwise not passed?

Or do I get it wrong, and the extractor would include the annotation-processed classes in the extracted unit?

Hopefully you have some idea - otherwise I could try to get a minimal reproduction. Thank you!

**Comment by shahms** [comment]
Processors should be run as part of extraction:
https://github.com/kythe/kythe/blob/master/kythe/java/com/google/devtools/kythe/extractors/java/JavaCompilationUnitExtractor.java#L186

**Comment by shahms** [comment]
(And the processor-generated sources should be included)

**Comment by robinp** [comment]
As I understand, Lombok does not generate sources (in contrast to AutoValue), but modifies the class file only. (Aside: it seems the modern idea of the Java community is that Lombok is arcane and AutoValue or Immutables is preferred. But let's put migration as a possible remedy aside for now).

So if I get it right, the change would only visible by either extracting the modified classes as well (which is not done), or re-running the processor as part of the indexing (which is not done either)?

**Comment by shahms** [comment]
@schroederc has been digging into the processor stuff a bit more recently, but that sounds plausible.  I suspect we'd want to extract the modified class files.

**Comment by robinp** [comment]
Thank you. As a remedy, I could try to use `delombok` to generate the sources - but that is somewhat inconvenient, as the sources that appear while browsing wouldn't correspond to the actual sources.

As for shipping the processed class files to the indexer - out of curiosity, would the indexer be able to act on the processed class files, while still taking into account the corresponding sources? For comments, spans, etc.

**Comment by schroederc** [comment]
A long time ago we looked at Lombok, but if I remember right, we didn't get very far because Google doesn't use it much and priorities changed.  I suspect we would need some special-casing to get it to work properly.

**Comment by robinp** [comment]
If Lombok is the only use-case for this scenario, then it is likely not worth the effort (given it is kind of deprecated). Let me get back in O(1) weeks if any workarounds are good-enough.
