### ISSUE TITLE
Kythe is failing with Bazel@HEAD due to the flip of incompatible_require_linker_input_cc_api

### ISSUE THREAD

**Issue by meteorcloudy** [kythe/kythe#4760]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1765#dc8119eb-6c19-4216-82a6-679b4bfebc48
```
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/5335be3f819e417ee04cbd9a2b000be5/external/com_github_google_brotli_go_cbrotli/BUILD:7:11: in go_library rule @com_github_google_brotli_go_cbrotli//:cbrotli:
Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/5335be3f819e417ee04cbd9a2b000be5/external/io_bazel_rules_go/go/private/rules/library.bzl", line 38, column 25, in _go_library_impl
		archive = go.archive(go, source)
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/5335be3f819e417ee04cbd9a2b000be5/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 82, column 28, in emit_archive
		cgo = cgo_configure(
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/5335be3f819e417ee04cbd9a2b000be5/external/io_bazel_rules_go/go/private/rules/cgo.bzl", line 112, column 31, in cgo_configure
		cc_libs = _cc_libs(d)
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/5335be3f819e417ee04cbd9a2b000be5/external/io_bazel_rules_go/go/private/rules/cgo.bzl", line 191, column 67, in _cc_libs
		libraries_to_link = as_iterable(target[CcInfo].linking_context.libraries_to_link)
Error: 'LinkingContext' value has no field or method 'libraries_to_link'
```
See https://github.com/bazelbuild/bazel/issues/10860

**Comment by shahms** [comment]
AFAICT this is a problem with upstream rules_go that is not yet fixed in the most recent release.  It's not something we can fix independently from that.

**Comment by shahms** [comment]
From the rules_go thread, this is fixed there but not yet present in a release.

**Comment by benjaminp** [comment]
I think this is fixed now.

**Comment by meteorcloudy** [comment]
Yes, Kythe is green on Bazel CI again
