### ISSUE TITLE
Error occurred during the fetch of repository 'souffle' with BAZEL@HEAD

### ISSUE THREAD

**Issue by sgowroji** [kythe/kythe#5864]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3332#018acfac-62a0-468d-8583-1eb93585739e

Platform : Ubuntu

Logs:
```
ERROR: An error occurred during the fetch of repository 'souffle':
   Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/e3a55cec1570d06656e66c4ad74b3af0/external/bazel_tools/tools/build_defs/repo/http.bzl", line 150, column 10, in _http_archive_impl
		patch(ctx, auth = auth)
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/e3a55cec1570d06656e66c4ad74b3af0/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 174, column 22, in patch
		ctx.patch(patchfile, strip)
Error in patch: Error applying patch /var/lib/buildkite-agent/builds/bk-docker-6x83/bazel-downstream-projects/kythe/third_party/souffle_filesystem.patch: in patch applied to /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/e3a55cec1570d06656e66c4ad74b3af0/external/souffle/src/include/souffle/utility/FileUtil.h: could not apply patch due to CONTENT_DOES_NOT_MATCH_TARGET
(04:11:37) ERROR: /var/lib/buildkite-agent/builds/bk-docker-6x83/bazel-downstream-projects/kythe/WORKSPACE:63:19: fetching http_archive rule //external:souffle: Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/e3a55cec1570d06656e66c4ad74b3af0/external/bazel_tools/tools/build_defs/repo/http.bzl", line 150, column 10, in _http_archive_impl
		patch(ctx, auth = auth)
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/e3a55cec1570d06656e66c4ad74b3af0/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 174, column 22, in patch
		ctx.patch(patchfile, strip)
Error in patch: Error applying patch /var/lib/buildkite-agent/builds/bk-docker-6x83/bazel-downstream-projects/kythe/third_party/souffle_filesystem.patch: in patch applied to /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/e3a55cec1570d06656e66c4ad74b3af0/external/souffle/src/include/souffle/utility/FileUtil.h: could not apply patch due to CONTENT_DOES_NOT_MATCH_TARGET
```

Steps:
```

git clone -v https://github.com/kythe/kythe.git
git reset 3a8d7b9f660b565152a27b799ecf083148a57c1b --hard
export USE_BAZEL_VERSION=ea4ab7d8e696f48253fd172fcfbd37661e4710d5
sudo apt update && sudo apt -y install bison flex uuid-dev asciidoc graphviz source-highlight
bazel build //kythe/...

```

CC Greenteam @Wyverald

**Comment by shahms** [comment]
That seems an awful lot like a bug in that particular Bazel version.  The patches apply cleanly locally, so I have no good way of investigating this.

**Comment by sgowroji** [comment]
@zrlk Any Update on the above issue ?

**Comment by shahms** [comment]
This is not repeatable using patch and seems a lot like a bazel bug.  There's not really anything we can do about it. The patch was generated directly from the source files Bazel is complaining about  so `CONTENT_DOES_NOT_MATCH_TARGET` is nonsensical.

**Comment by meteorcloudy** [comment]
I'll take a look

**Comment by meteorcloudy** [comment]
It seems to be an issue in the [`applyFuzz`](https://github.com/bazelbuild/bazel/commit/5c843397d9f2da548ec5f5b4a75b4be74b42df74#diff-52b252e221ccdfabe8f9967093d3190c8cd287512ab7f7b353fa7dd8889556b9R218) function, I guess we can switch to `applyTo` without fuzz matching.

**Comment by meteorcloudy** [comment]
Should be fixed by https://github.com/bazelbuild/bazel/commit/555d7e51c980d27c7499dadffcedc3d741a9b269

**Comment by Wyverald** [comment]
Please close; this is fixed
