### ISSUE TITLE
[Bazel CI] FATAL: Bazel crashed due to an internal error while evaluating node


### ISSUE THREAD

**Issue by sgowroji** [kythe/kythe#6135]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4089#0191a183-3d73-4aad-af20-b1c2ee0d7b40

 Platform: Ubuntu

 Logs: 
```
bazel --nosystem_rc --nohome_rc info
WARNING: Option 'experimental_strict_action_env' is deprecated: Use --incompatible_strict_action_env instead
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: java.lang.RuntimeException: Unrecoverable error while evaluating node 'PlatformMappingValue.Key{path=platform_mappings, wasExplicitlySetByUser=false}' (requested by nodes 'BuildConfigurationKeyValue.Key{buildOptions=d0337467a81a2969d7626e84b637953bdd8f392ca5ff0e265d89c1d577613a1e}')
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.evaluateSkyKeys(SkyframeExecutor.java:2026)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.evaluateSkyKeys(SkyframeExecutor.java:2002)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.createBuildConfigurationKey(SkyframeExecutor.java:1958)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.getConfiguration(SkyframeExecutor.java:1882)
	at com.google.devtools.build.lib.runtime.commands.InfoCommand.lambda$exec$0(InfoCommand.java:158)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
	at com.google.devtools.build.lib.runtime.commands.InfoCommand.exec(InfoCommand.java:219)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:679)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:252)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:607)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$1(GrpcServerImpl.java:676)
	at io.grpc.Context$1.run(Context.java:566)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Unrecoverable error while evaluating node 'PlatformMappingValue.Key{path=platform_mappings, wasExplicitlySetByUser=false}' (requested by nodes 'BuildConfigurationKeyValue.Key{buildOptions=d0337467a81a2969d7626e84b637953bdd8f392ca5ff0e265d89c1d577613a1e}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:547)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Null repoMapping
	at com.google.devtools.build.lib.cmdline.AutoValue_Label_RepoContextImpl.<init>(AutoValue_Label_RepoContextImpl.java:20)
	at com.google.devtools.build.lib.cmdline.Label$RepoContext.of(Label.java:122)
	at com.google.devtools.build.lib.skyframe.config.PlatformMappingFunction.compute(PlatformMappingFunction.java:82)
	at com.google.devtools.build.lib.skyframe.config.PlatformMappingFunction.compute(PlatformMappingFunction.java:60)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:467)
	... 7 more
``` 
 Culprit: https://github.com/bazelbuild/bazel/commit/5881c38c54416add9faec35b7731954f4baf12d8

 Steps:
  ``` 
 git clone https://github.com/kythe/kythe
git reset 75f63c532eeba9592650d6b1b62ec93071e9a7db  --hard
export USE_BAZEL_VERSION=ed8ed01cf3c86485dbd1d756b6e891daad892358 
 ``` 
 CC Greenteam @mai93

**Comment by lfolger** [comment]
This looks like an internal bazel crash. Why is this filed in the Kythe repository?

**Comment by sgowroji** [comment]
This is about bazelmod conversion. based on the culprit ([bazelbuild/bazel@5881c38](https://github.com/bazelbuild/bazel/commit/5881c38c54416add9faec35b7731954f4baf12d8)) in the issue description, you may need to add `--enable_workspace` explicitly as it is flipped to `false` in bazel @ head

**Comment by meisterT** [comment]
but bazel should not crash regardless, cc @Wyverald

**Comment by Wyverald** [comment]
I have a Bazel change incoming to fix the crash.

@lfolger: Bazel 8.0 will flip the default value of `--enable_workspace` (introduced in 7.1.0) to false. Kythe has `--enable_bzlmod` set to false in its .bazelrc (https://github.com/kythe/kythe/blob/e35bed7032a7c605fa99b5e97fa32b9104e7bfdd/.bazelrc#L18). Both flags can't be false at the same time, so this is is an early warning that Kythe will break with 8.0; you could simply delay this by explicitly setting `--enable_workspace` to true in your .bazelrc. (But obviously better if you migrate to Bzlmod!)

**Comment by shahms** [comment]
FWIW, when I looked into supporting bzlmod, the major blocker was protobuf.  As that seems to support bzlmod now, I suspect doing the migration should at least be feasible now. There will be some C++ dependencies which can't support bzlmod. ISTR at least one BUILD-file patch required using the "fully qualified" repository name for a difference dependency so that will complicate migration until https://github.com/bazelbuild/bazel/issues/19301 is addressed.
